name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap environment
        run: bash scripts/background/setup.sh

      - name: Run CI script (lint, types, tests, build)
        run: bash scripts/background/ci.sh

